<?php

return [
    'reference_sources' => [
        'usage_mapping' => [
            'table' => 'ref_usage_to_mappi_group',
            'purpose' => 'Memetakan peruntukan aset internal ke tipe dan kelas bangunan MAPPI.',
            'filters' => ['peruntukan_enum'],
        ],
        'cost_elements' => [
            'table' => 'ref_cost_elements',
            'purpose' => 'Biaya unit terpasang per elemen dan spesifikasi material dari sheet BUT_Print.',
            'filters' => ['guideline_set_id', 'year', 'base_region', 'building_type', 'building_class', 'storey_pattern', 'element_code'],
        ],
        'mappi_rcn' => [
            'table' => 'ref_mappi_rcn_standards',
            'purpose' => 'RCN baseline per tipe, kelas, dan pola lantai.',
            'filters' => ['guideline_set_id', 'year', 'reference_region', 'building_type', 'building_class', 'storey_pattern'],
        ],
        'floor_index' => [
            'table' => 'ref_floor_index',
            'purpose' => 'Indeks jumlah lantai berdasarkan kelas bangunan dan jumlah lantai.',
            'filters' => ['guideline_set_id', 'year', 'building_class', 'floor_count'],
        ],
        'economic_life' => [
            'table' => 'ref_building_economic_life',
            'purpose' => 'Umur ekonomis bangunan untuk depresiasi.',
            'filters' => ['guideline_item_id', 'year', 'building_type', 'building_class', 'storey_min', 'storey_max'],
        ],
        'construction_cost_index' => [
            'table' => 'ref_construction_cost_index',
            'purpose' => 'IKK wilayah penilaian untuk penyesuaian biaya langsung.',
            'filters' => ['guideline_set_id', 'year', 'region_code'],
        ],
    ],

    'worksheet_columns' => [
        'standard_side' => [
            'element' => 'Elemen Bangunan',
            'material_spec' => 'Spesifikasi Material Model',
            'unit_cost' => 'Biaya Unit Terpasang',
            'volume_percent' => 'Volume (%)',
            'line_total' => 'BRB x Volume',
        ],
        'subject_side' => [
            'element' => 'Elemen Bangunan',
            'material_spec' => 'Spesifikasi Material Objek yang Dinilai',
            'unit_cost' => 'Biaya Unit Terpasang',
            'volume_percent' => 'Volume (%)',
            'other_adjustment_factor' => 'Adjusment Lain',
            'direct_cost_result' => 'Hasil Perhitungan Biaya Langsung',
        ],
    ],

    'field_sources' => [
        'asset' => [
            'building_area',
            'floor_count',
            'building_name',
            'building_year',
            'regency_id',
            'property_usage',
        ],
        'reviewer_input' => [
            'worksheet_template',
            'subject_material_spec',
            'subject_volume_percent',
            'other_adjustment_factor',
            'effective_age',
            'notes',
        ],
        'reference' => [
            'building_type',
            'building_class',
            'storey_pattern',
            'ref_unit_cost',
            'ikk_value',
            'economic_life',
            'il_value',
            'rcn_value',
        ],
        'calculated' => [
            'hard_cost_total',
            'soft_cost_total',
            'total_rcn',
            'depreciation_percent',
            'total_depreciated_value',
            'residual_land_value',
            'residual_land_value_per_sqm',
        ],
    ],

    'sections' => [
        'hard_cost' => [
            'label' => 'A. BIAYA LANGSUNG (HARDCOST)',
            'line_codes' => [
                'foundation',
                'structure',
                'roof_frame',
                'roof_cover',
                'ceiling',
                'wall',
                'door_window',
                'floor_finish',
                'utilities',
                'hard_cost_total',
                'hard_cost_total_ikk',
                'hard_cost_total_ikk_floor_index',
            ],
        ],
        'indirect_cost' => [
            'label' => 'B. BIAYA TAK LANGSUNG',
            'line_codes' => [
                'professional_fee',
                'permit_cost',
                'contractor_profit',
                'indirect_cost_total',
            ],
        ],
        'depreciation' => [
            'label' => 'DEPRESIASI',
            'line_codes' => [
                'depreciation_per_sqm',
                'depreciated_brb_per_sqm',
                'depreciated_brb_total',
            ],
        ],
    ],

    'indirect_cost_factors' => [
        'professional_fee' => 0.03,
        'permit_cost' => 0.015,
        'contractor_profit' => 0.10,
    ],

    'line_items' => [
        'foundation' => [
            'label' => 'Pondasi',
            'section' => 'hard_cost',
            'reference_group' => 'PONDASI',
            'type' => 'element',
        ],
        'structure' => [
            'label' => 'Struktur',
            'section' => 'hard_cost',
            'reference_group' => 'STRUKTUR',
            'type' => 'element',
        ],
        'roof_frame' => [
            'label' => 'Rangka Atap',
            'section' => 'hard_cost',
            'reference_group' => 'RANGKA ATAP',
            'type' => 'element',
        ],
        'roof_cover' => [
            'label' => 'Penutup Atap',
            'section' => 'hard_cost',
            'reference_group' => 'PENUTUP ATAP',
            'type' => 'element',
        ],
        'ceiling' => [
            'label' => 'Plafond',
            'section' => 'hard_cost',
            'reference_group' => 'PLAFOND',
            'type' => 'element',
        ],
        'wall' => [
            'label' => 'Dinding',
            'section' => 'hard_cost',
            'reference_group' => 'DINDING',
            'type' => 'element',
        ],
        'door_window' => [
            'label' => 'Pintu & Jendela',
            'section' => 'hard_cost',
            'reference_group' => 'PINTU & JENDELA',
            'type' => 'element',
        ],
        'floor_finish' => [
            'label' => 'Lantai',
            'section' => 'hard_cost',
            'reference_group' => 'LANTAI',
            'type' => 'element',
        ],
        'utilities' => [
            'label' => 'Utilitas',
            'section' => 'hard_cost',
            'reference_group' => 'UTILITAS',
            'type' => 'element',
        ],
        'hard_cost_total' => [
            'label' => 'Total Biaya Langsung',
            'section' => 'hard_cost',
            'type' => 'subtotal',
        ],
        'hard_cost_total_ikk' => [
            'label' => 'Total Biaya Langsung Adjusment IKK',
            'section' => 'hard_cost',
            'type' => 'derived_subtotal',
        ],
        'hard_cost_total_ikk_floor_index' => [
            'label' => 'Total Biaya Langsung Adjusment IKK & Indeks Lantai (A)',
            'section' => 'hard_cost',
            'type' => 'derived_subtotal',
        ],
        'professional_fee' => [
            'label' => 'Profesional Fee',
            'section' => 'indirect_cost',
            'type' => 'factor',
        ],
        'permit_cost' => [
            'label' => 'Biaya Perijinan',
            'section' => 'indirect_cost',
            'type' => 'factor',
        ],
        'contractor_profit' => [
            'label' => 'Keuntungan Kontraktor',
            'section' => 'indirect_cost',
            'type' => 'factor',
        ],
        'indirect_cost_total' => [
            'label' => 'Total Biaya Tak Langsung',
            'section' => 'indirect_cost',
            'type' => 'subtotal',
        ],
        'depreciation_per_sqm' => [
            'label' => 'DEPRESIASI (Rp/m2)',
            'section' => 'depreciation',
            'type' => 'derived',
        ],
        'depreciated_brb_per_sqm' => [
            'label' => 'BRB Terdepresiasi (Rp/m2)',
            'section' => 'depreciation',
            'type' => 'derived',
        ],
        'depreciated_brb_total' => [
            'label' => 'BRB Terdepr x Luas (Rp)',
            'section' => 'depreciation',
            'type' => 'derived_total',
        ],
    ],

    'template_aliases' => [
        'MEWAH' => 'rumah_mewah',
        'MENENGAH' => 'rumah_menengah',
        'SEDERHANA' => 'rumah_sederhana',
        'SEMI PERMANEN' => 'semi_permanen',
        'SEMI_PERMANEN' => 'semi_permanen',
        'GUDANG' => 'gudang',
        'LOW RISE' => 'low_rise_building',
        'LOW_RISE' => 'low_rise_building',
        'LOW RISE BUILDING' => 'low_rise_building',
        'RUKO' => 'low_rise_building',
    ],

    'usage_defaults' => [
        'tanah_kosong' => [
            'uses_btb' => false,
            'candidate_templates' => [],
        ],
        'rumah_tinggal' => [
            'uses_btb' => true,
            'candidate_templates' => ['rumah_sederhana', 'rumah_menengah', 'rumah_mewah'],
            'default_template' => 'rumah_sederhana',
            'mappi_building_type' => 'BANGUNAN_RUMAH_TINGGAL',
        ],
        'ruko' => [
            'uses_btb' => true,
            'candidate_templates' => ['low_rise_building'],
            'default_template' => 'low_rise_building',
            'mappi_building_type' => 'RUKO',
        ],
        'kantor' => [
            'uses_btb' => true,
            'candidate_templates' => ['low_rise_building'],
            'default_template' => 'low_rise_building',
            'mappi_building_type' => 'BANGUNAN_GEDUNG_BERTINGKAT',
            'mappi_building_class' => 'LOW_RISE',
        ],
        'gudang' => [
            'uses_btb' => true,
            'candidate_templates' => ['gudang', 'semi_permanen'],
            'default_template' => 'gudang',
            'mappi_building_type' => 'BANGUNAN_GUDANG',
        ],
        'pabrik' => [
            'uses_btb' => true,
            'candidate_templates' => ['gudang', 'semi_permanen'],
            'default_template' => 'gudang',
            'mappi_building_type' => 'BANGUNAN_GUDANG',
        ],
        'apartement' => [
            'uses_btb' => true,
            'candidate_templates' => ['low_rise_building'],
            'default_template' => 'low_rise_building',
            'mappi_building_type' => 'MODEL_APARTEMEN',
        ],
        'kios' => [
            'uses_btb' => true,
            'candidate_templates' => ['low_rise_building'],
            'default_template' => 'low_rise_building',
            'mappi_building_type' => 'RUKO',
        ],
        'tanah_kebun' => [
            'uses_btb' => false,
            'candidate_templates' => [],
        ],
        'sawah' => [
            'uses_btb' => false,
            'candidate_templates' => [],
        ],
    ],

    'templates' => [
        'rumah_mewah' => [
            'label' => 'Rumah Tinggal Mewah',
            'sheet_name' => 'R. Mewah',
            'usage_options' => ['rumah_tinggal'],
            'mappi_building_type' => 'BANGUNAN_RUMAH_TINGGAL',
            'mappi_building_class' => 'MEWAH',
            'storey_pattern' => '2 Lantai',
            'default_floor_count' => 2,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
        'rumah_menengah' => [
            'label' => 'Rumah Tinggal Menengah',
            'sheet_name' => 'R. Menengah',
            'usage_options' => ['rumah_tinggal'],
            'mappi_building_type' => 'BANGUNAN_RUMAH_TINGGAL',
            'mappi_building_class' => 'MENENGAH',
            'storey_pattern' => '2 Lantai',
            'default_floor_count' => 2,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
        'rumah_sederhana' => [
            'label' => 'Rumah Tinggal Sederhana',
            'sheet_name' => 'R.Sederhana',
            'usage_options' => ['rumah_tinggal'],
            'mappi_building_type' => 'BANGUNAN_RUMAH_TINGGAL',
            'mappi_building_class' => 'SEDERHANA',
            'storey_pattern' => '1 Lantai',
            'default_floor_count' => 1,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
        'semi_permanen' => [
            'label' => 'Bangunan Semi Permanen',
            'sheet_name' => 'Semi Permanen',
            'usage_options' => ['gudang', 'pabrik'],
            'mappi_building_type' => 'BGN. PERKEBUNAN (SEMI PERMANEN)',
            'mappi_building_class' => 'SEMI PERMANEN',
            'storey_pattern' => '1 Lantai',
            'default_floor_count' => 1,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
        'gudang' => [
            'label' => 'Bangunan Gudang',
            'sheet_name' => 'Gudang',
            'usage_options' => ['gudang', 'pabrik'],
            'mappi_building_type' => 'BANGUNAN_GUDANG',
            'mappi_building_class' => 'GUDANG',
            'storey_pattern' => '1 Lantai',
            'default_floor_count' => 1,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
        'low_rise_building' => [
            'label' => 'Low Rise Building / Ruko',
            'sheet_name' => 'Low Rise Building',
            'usage_options' => ['ruko', 'kantor', 'kios', 'apartement'],
            'mappi_building_type' => 'BANGUNAN_GEDUNG_BERTINGKAT',
            'mappi_building_class' => 'LOW_RISE',
            'storey_pattern' => '3 Lantai',
            'default_floor_count' => 3,
            'reference_region' => 'DKI Jakarta',
            'cost_source_sheet' => 'BUT_Print',
            'section_codes' => ['hard_cost', 'indirect_cost', 'depreciation'],
        ],
    ],
];
