<?php

namespace App\Support;

class SystemSectionNavigationRegistry
{
    public static function items(): array
    {
        return [
            [
                'key' => 'reviewer.dashboard',
                'label' => 'Dashboard',
                'icon' => 'LayoutDashboard',
                'surface' => 'reviewer',
                'routeName' => 'reviewer.dashboard',
                'activePatterns' => ['reviewer.dashboard'],
                'pathPrefixes' => ['/reviewer'],
                'requiredPermission' => SystemNavigation::ACCESS_REVIEWER_DASHBOARD,
            ],
            [
                'key' => 'reviewer.reviews',
                'label' => 'Review',
                'icon' => 'ClipboardList',
                'surface' => 'reviewer',
                'routeName' => 'reviewer.reviews.index',
                'activePatterns' => ['reviewer.reviews.*', 'reviewer.assets.*'],
                'pathPrefixes' => ['/reviewer/reviews', '/reviewer/assets'],
                'requiredPermission' => SystemNavigation::MANAGE_REVIEWER_REVIEWS,
            ],
            [
                'key' => 'reviewer.comparables',
                'label' => 'Comparables',
                'icon' => 'Scale',
                'surface' => 'reviewer',
                'routeName' => 'reviewer.comparables.index',
                'activePatterns' => ['reviewer.comparables.*'],
                'pathPrefixes' => ['/reviewer/comparables'],
                'requiredPermission' => SystemNavigation::MANAGE_REVIEWER_COMPARABLES,
            ],
            [
                'key' => 'admin.dashboard',
                'label' => 'Dashboard',
                'icon' => 'LayoutDashboard',
                'surface' => 'admin',
                'routeName' => 'admin.dashboard',
                'activePatterns' => ['admin.dashboard'],
                'exactPaths' => ['/admin'],
                'requiredPermission' => SystemNavigation::ACCESS_ADMIN_DASHBOARD,
            ],
            [
                'key' => 'admin.requests',
                'label' => 'Permohonan',
                'icon' => 'ClipboardList',
                'surface' => 'admin',
                'routeName' => 'admin.appraisal-requests.index',
                'activePatterns' => ['admin.appraisal-requests.*'],
                'pathPrefixes' => ['/admin/permohonan-penilaian'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_APPRAISAL_REQUESTS,
                'subItems' => [
                    [
                        'key' => 'admin.requests.index',
                        'label' => 'Request',
                        'icon' => 'ClipboardList',
                        'routeName' => 'admin.appraisal-requests.index',
                        'activePatterns' => ['admin.appraisal-requests.index', 'admin.appraisal-requests.show', 'admin.appraisal-requests.edit', 'admin.appraisal-requests.update', 'admin.appraisal-requests.actions.*', 'admin.appraisal-requests.revision-batches.*', 'admin.appraisal-requests.field-corrections.*', 'admin.appraisal-requests.revision-items.*'],
                        'pathPrefixes' => ['/admin/permohonan-penilaian'],
                    ],
                    [
                        'key' => 'admin.requests.cancellations',
                        'label' => 'Pembatalan Request',
                        'icon' => 'CircleSlash2',
                        'routeName' => 'admin.appraisal-requests.cancellations.index',
                        'activePatterns' => ['admin.appraisal-requests.cancellations.*'],
                        'pathPrefixes' => ['/admin/permohonan-penilaian/pembatalan'],
                    ],
                ],
            ],
            [
                'key' => 'admin.finance',
                'label' => 'Keuangan',
                'icon' => 'CreditCard',
                'surface' => 'admin',
                'routeName' => 'admin.finance.payments.index',
                'activePatterns' => ['admin.finance.*'],
                'pathPrefixes' => ['/admin/keuangan'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_FINANCE,
            ],
            [
                'key' => 'reviewer.master-data',
                'label' => 'Master Data',
                'icon' => 'MapPinned',
                'surface' => 'reviewer',
                'routeName' => 'reviewer.master-data.provinces.index',
                'activePatterns' => ['reviewer.master-data.*'],
                'pathPrefixes' => ['/reviewer/master-data'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_MASTER_DATA,
                'subItems' => [
                    [
                        'key' => 'reviewer.master-data.provinces',
                        'label' => 'Provinsi',
                        'icon' => 'Map',
                        'routeName' => 'reviewer.master-data.provinces.index',
                        'activePatterns' => ['reviewer.master-data.provinces.*'],
                        'pathPrefixes' => ['/reviewer/master-data/provinsi'],
                    ],
                    [
                        'key' => 'reviewer.master-data.regencies',
                        'label' => 'Kabupaten/Kota',
                        'icon' => 'Building2',
                        'routeName' => 'reviewer.master-data.regencies.index',
                        'activePatterns' => ['reviewer.master-data.regencies.*'],
                        'pathPrefixes' => ['/reviewer/master-data/kabupaten-kota'],
                    ],
                    [
                        'key' => 'reviewer.master-data.districts',
                        'label' => 'Kecamatan',
                        'icon' => 'MapPinned',
                        'routeName' => 'reviewer.master-data.districts.index',
                        'activePatterns' => ['reviewer.master-data.districts.*'],
                        'pathPrefixes' => ['/reviewer/master-data/kecamatan'],
                    ],
                    [
                        'key' => 'reviewer.master-data.villages',
                        'label' => 'Kelurahan/Desa',
                        'icon' => 'House',
                        'routeName' => 'reviewer.master-data.villages.index',
                        'activePatterns' => ['reviewer.master-data.villages.*'],
                        'pathPrefixes' => ['/reviewer/master-data/kelurahan-desa'],
                    ],
                ],
            ],
            [
                'key' => 'reviewer.ref-guidelines',
                'label' => 'Pedoman Referensi',
                'icon' => 'BookOpen',
                'surface' => 'reviewer',
                'routeName' => 'reviewer.ref-guidelines.guideline-sets.index',
                'activePatterns' => ['reviewer.ref-guidelines.*'],
                'pathPrefixes' => ['/reviewer/ref-guidelines'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_REF_GUIDELINES,
                'subItems' => [
                    [
                        'key' => 'reviewer.ref-guidelines.guideline-sets',
                        'label' => 'Set Pedoman',
                        'icon' => 'BookText',
                        'routeName' => 'reviewer.ref-guidelines.guideline-sets.index',
                        'activePatterns' => ['reviewer.ref-guidelines.guideline-sets.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/guideline-sets'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.construction-cost-indices',
                        'label' => 'Indeks Kemahalan Konstruksi',
                        'icon' => 'Factory',
                        'routeName' => 'reviewer.ref-guidelines.construction-cost-indices.index',
                        'activePatterns' => ['reviewer.ref-guidelines.construction-cost-indices.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/ikk'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.cost-elements',
                        'label' => 'Biaya Unit Terpasang',
                        'icon' => 'Layers3',
                        'routeName' => 'reviewer.ref-guidelines.cost-elements.index',
                        'activePatterns' => ['reviewer.ref-guidelines.cost-elements.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/cost-elements'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.floor-indices',
                        'label' => 'Indeks Lantai',
                        'icon' => 'Building2',
                        'routeName' => 'reviewer.ref-guidelines.floor-indices.index',
                        'activePatterns' => ['reviewer.ref-guidelines.floor-indices.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/floor-indices'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.mappi-rcn-standards',
                        'label' => 'MAPPI RCN',
                        'icon' => 'Ruler',
                        'routeName' => 'reviewer.ref-guidelines.mappi-rcn-standards.index',
                        'activePatterns' => ['reviewer.ref-guidelines.mappi-rcn-standards.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/mappi-rcn-standards'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.building-economic-lives',
                        'label' => 'Umur Ekonomis Bangunan',
                        'icon' => 'BookMarked',
                        'routeName' => 'reviewer.ref-guidelines.building-economic-lives.index',
                        'activePatterns' => ['reviewer.ref-guidelines.building-economic-lives.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/building-economic-lives'],
                    ],
                    [
                        'key' => 'reviewer.ref-guidelines.valuation-settings',
                        'label' => 'Pengaturan Valuasi',
                        'icon' => 'ClipboardList',
                        'routeName' => 'reviewer.ref-guidelines.valuation-settings.index',
                        'activePatterns' => ['reviewer.ref-guidelines.valuation-settings.*'],
                        'pathPrefixes' => ['/reviewer/ref-guidelines/valuation-settings'],
                    ],
                ],
            ],
            [
                'key' => 'admin.master-data',
                'label' => 'Master Data',
                'icon' => 'MapPinned',
                'surface' => 'admin',
                'routeName' => 'admin.master-data.provinces.index',
                'activePatterns' => ['admin.master-data.*'],
                'pathPrefixes' => ['/admin/master-data'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_MASTER_DATA,
                'subItems' => [
                    [
                        'key' => 'admin.master-data.users',
                        'label' => 'User Terdaftar',
                        'icon' => 'Users',
                        'routeName' => 'admin.master-data.users.index',
                        'activePatterns' => ['admin.master-data.users.*'],
                        'pathPrefixes' => ['/admin/master-data/users'],
                        'requiredPermission' => SystemNavigation::MANAGE_ADMIN_MASTER_DATA_USERS,
                    ],
                    [
                        'key' => 'admin.master-data.report-signers',
                        'label' => 'Penandatangan Report',
                        'icon' => 'FileText',
                        'routeName' => 'admin.master-data.report-signers.index',
                        'activePatterns' => ['admin.master-data.report-signers.*'],
                        'pathPrefixes' => ['/admin/master-data/penandatangan-report'],
                    ],
                    [
                        'key' => 'admin.master-data.provinces',
                        'label' => 'Provinsi',
                        'icon' => 'Map',
                        'routeName' => 'admin.master-data.provinces.index',
                        'activePatterns' => ['admin.master-data.provinces.*'],
                        'pathPrefixes' => ['/admin/master-data/provinsi'],
                    ],
                    [
                        'key' => 'admin.master-data.regencies',
                        'label' => 'Kabupaten/Kota',
                        'icon' => 'Building2',
                        'routeName' => 'admin.master-data.regencies.index',
                        'activePatterns' => ['admin.master-data.regencies.*'],
                        'pathPrefixes' => ['/admin/master-data/kabupaten-kota'],
                    ],
                    [
                        'key' => 'admin.master-data.districts',
                        'label' => 'Kecamatan',
                        'icon' => 'MapPinned',
                        'routeName' => 'admin.master-data.districts.index',
                        'activePatterns' => ['admin.master-data.districts.*'],
                        'pathPrefixes' => ['/admin/master-data/kecamatan'],
                    ],
                    [
                        'key' => 'admin.master-data.villages',
                        'label' => 'Kelurahan/Desa',
                        'icon' => 'House',
                        'routeName' => 'admin.master-data.villages.index',
                        'activePatterns' => ['admin.master-data.villages.*'],
                        'pathPrefixes' => ['/admin/master-data/kelurahan-desa'],
                    ],
                ],
            ],
            [
                'key' => 'admin.ref-guidelines',
                'label' => 'Pedoman Referensi',
                'icon' => 'BookOpen',
                'surface' => 'admin',
                'routeName' => 'admin.ref-guidelines.guideline-sets.index',
                'activePatterns' => ['admin.ref-guidelines.*'],
                'pathPrefixes' => ['/admin/ref-guidelines'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_REF_GUIDELINES,
                'subItems' => [
                    [
                        'key' => 'admin.ref-guidelines.guideline-sets',
                        'label' => 'Set Pedoman',
                        'icon' => 'BookText',
                        'routeName' => 'admin.ref-guidelines.guideline-sets.index',
                        'activePatterns' => ['admin.ref-guidelines.guideline-sets.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/guideline-sets'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.construction-cost-indices',
                        'label' => 'Indeks Kemahalan Konstruksi',
                        'icon' => 'Factory',
                        'routeName' => 'admin.ref-guidelines.construction-cost-indices.index',
                        'activePatterns' => ['admin.ref-guidelines.construction-cost-indices.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/ikk'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.cost-elements',
                        'label' => 'Biaya Unit Terpasang',
                        'icon' => 'Layers3',
                        'routeName' => 'admin.ref-guidelines.cost-elements.index',
                        'activePatterns' => ['admin.ref-guidelines.cost-elements.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/cost-elements'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.floor-indices',
                        'label' => 'Indeks Lantai',
                        'icon' => 'Building2',
                        'routeName' => 'admin.ref-guidelines.floor-indices.index',
                        'activePatterns' => ['admin.ref-guidelines.floor-indices.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/floor-indices'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.mappi-rcn-standards',
                        'label' => 'MAPPI RCN',
                        'icon' => 'Ruler',
                        'routeName' => 'admin.ref-guidelines.mappi-rcn-standards.index',
                        'activePatterns' => ['admin.ref-guidelines.mappi-rcn-standards.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/mappi-rcn-standards'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.building-economic-lives',
                        'label' => 'Umur Ekonomis Bangunan',
                        'icon' => 'BookMarked',
                        'routeName' => 'admin.ref-guidelines.building-economic-lives.index',
                        'activePatterns' => ['admin.ref-guidelines.building-economic-lives.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/building-economic-lives'],
                    ],
                    [
                        'key' => 'admin.ref-guidelines.valuation-settings',
                        'label' => 'Pengaturan Valuasi',
                        'icon' => 'ClipboardList',
                        'routeName' => 'admin.ref-guidelines.valuation-settings.index',
                        'activePatterns' => ['admin.ref-guidelines.valuation-settings.*'],
                        'pathPrefixes' => ['/admin/ref-guidelines/valuation-settings'],
                    ],
                ],
            ],
            [
                'key' => 'admin.access-control',
                'label' => 'Hak Akses',
                'icon' => 'LockKeyhole',
                'surface' => 'admin',
                'routeName' => 'admin.access-control.roles.index',
                'activePatterns' => ['admin.access-control.*'],
                'pathPrefixes' => ['/admin/hak-akses'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_ACCESS_CONTROL,
            ],
            [
                'key' => 'admin.content',
                'label' => 'Konten',
                'icon' => 'BookOpen',
                'surface' => 'admin',
                'routeName' => 'admin.content.articles.index',
                'activePatterns' => ['admin.content.*', 'admin.content.legal.*'],
                'pathPrefixes' => ['/admin/konten'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_CONTENT,
                'subItems' => [
                    [
                        'key' => 'admin.content.articles',
                        'label' => 'Artikel',
                        'icon' => 'BookText',
                        'routeName' => 'admin.content.articles.index',
                        'activePatterns' => ['admin.content.articles.*'],
                        'pathPrefixes' => ['/admin/konten/artikel'],
                    ],
                    [
                        'key' => 'admin.content.categories',
                        'label' => 'Kategori Artikel',
                        'icon' => 'FolderTree',
                        'routeName' => 'admin.content.categories.index',
                        'activePatterns' => ['admin.content.categories.*'],
                        'pathPrefixes' => ['/admin/konten/kategori-artikel'],
                    ],
                    [
                        'key' => 'admin.content.tags',
                        'label' => 'Tag',
                        'icon' => 'Tags',
                        'routeName' => 'admin.content.tags.index',
                        'activePatterns' => ['admin.content.tags.*'],
                        'pathPrefixes' => ['/admin/konten/tag'],
                    ],
                    [
                        'key' => 'admin.legal.faqs',
                        'label' => 'FAQ',
                        'icon' => 'CircleHelp',
                        'routeName' => 'admin.content.legal.faqs.index',
                        'activePatterns' => ['admin.content.legal.faqs.*'],
                        'pathPrefixes' => ['/admin/konten/legal/faq'],
                    ],
                    [
                        'key' => 'admin.legal.features',
                        'label' => 'Fitur',
                        'icon' => 'Sparkles',
                        'routeName' => 'admin.content.legal.features.index',
                        'activePatterns' => ['admin.content.legal.features.*'],
                        'pathPrefixes' => ['/admin/konten/legal/fitur'],
                    ],
                    [
                        'key' => 'admin.legal.testimonials',
                        'label' => 'Testimoni',
                        'icon' => 'MessageSquareQuote',
                        'routeName' => 'admin.content.legal.testimonials.index',
                        'activePatterns' => ['admin.content.legal.testimonials.*'],
                        'pathPrefixes' => ['/admin/konten/legal/testimoni'],
                    ],
                    [
                        'key' => 'admin.legal.terms',
                        'label' => 'Terms',
                        'icon' => 'ScrollText',
                        'routeName' => 'admin.content.legal.terms.index',
                        'activePatterns' => ['admin.content.legal.terms.*'],
                        'pathPrefixes' => ['/admin/konten/legal/terms'],
                    ],
                    [
                        'key' => 'admin.legal.privacy',
                        'label' => 'Privacy',
                        'icon' => 'ShieldCheck',
                        'routeName' => 'admin.content.legal.privacy.index',
                        'activePatterns' => ['admin.content.legal.privacy.*'],
                        'pathPrefixes' => ['/admin/konten/legal/privacy'],
                    ],
                    [
                        'key' => 'admin.legal.consent',
                        'label' => 'Consent',
                        'icon' => 'FileText',
                        'routeName' => 'admin.content.legal.consent.index',
                        'activePatterns' => ['admin.content.legal.consent.*'],
                        'pathPrefixes' => ['/admin/konten/legal/consent'],
                    ],
                    [
                        'key' => 'admin.legal.user-consents',
                        'label' => 'Audit Consent',
                        'icon' => 'ClipboardCheck',
                        'routeName' => 'admin.content.legal.user-consents.index',
                        'activePatterns' => ['admin.content.legal.user-consents.*'],
                        'pathPrefixes' => ['/admin/konten/legal/persetujuan-pengguna'],
                    ],
                ],
            ],
            [
                'key' => 'admin.communications',
                'label' => 'Komunikasi',
                'icon' => 'Mail',
                'surface' => 'admin',
                'routeName' => 'admin.communications.contact-messages.index',
                'activePatterns' => ['admin.communications.*'],
                'pathPrefixes' => ['/admin/komunikasi'],
                'requiredPermission' => SystemNavigation::MANAGE_ADMIN_COMMUNICATIONS,
                'subItems' => [
                    [
                        'key' => 'admin.communications.contact-messages',
                        'label' => 'Contact Message',
                        'icon' => 'Mail',
                        'routeName' => 'admin.communications.contact-messages.index',
                        'activePatterns' => ['admin.communications.contact-messages.*'],
                        'pathPrefixes' => ['/admin/komunikasi/contact-messages'],
                    ],
                    [
                        'key' => 'admin.communications.support-contact',
                        'label' => 'Support Contact',
                        'icon' => 'CircleHelp',
                        'routeName' => 'admin.communications.support-contact.edit',
                        'activePatterns' => ['admin.communications.support-contact.*'],
                        'pathPrefixes' => ['/admin/komunikasi/support-contact'],
                    ],
                ],
            ],
        ];
    }
}
